name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: marocchino/setup-terraform@v1
      with:
        version: "0.12.24"
    - run: terraform fmt -check=true -write=false -diff -recursive
    - run: terraform validate
